#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-generex
Version  : 1.0.0
Release  : 3
URL      : https://github.com/mifmif/Generex/archive/1.0.0.tar.gz
Source0  : https://github.com/mifmif/Generex/archive/1.0.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/mifmif/generex/1.0.1/generex-1.0.1.jar
Source2  : https://repo1.maven.org/maven2/com/github/mifmif/generex/1.0.1/generex-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-generex-data = %{version}-%{release}

%description
Generex
=======
A Java library for generating String that match  a given regular expression. it help you generate all Strings that matches a given Regex, random one , or one String from the matched String based on it's index.
Generex is based on the library http://www.brics.dk/~amoeller/automaton/.

%package data
Summary: data components for the mvn-generex package.
Group: Data

%description data
data components for the mvn-generex package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.jar
/usr/share/java/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.pom
